### PR TITLE
User interface Milestone

### PR DESCRIPTION
**Pull request by Victorgonbu**
For this milestone we have created the interface for players.

# Obtained
- Player name
- Player symbol 
- Player move

# Added

- Tic tac toe board structure
- Tic tac toe board
-  Inline comments describing game logic

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Shaqri and @Prabhakarzx 
### You have done well so far :clap: However, you need to make a few changes to the project.
- [x] game asks players for their names
- [x] game tells which player turn it is
- [x] game asks the player to select from available moves
- [x] game informs player if the selected move is invalid
- [x] game displays board after the player move
- [x] game informs player if the selected move is a winning move
- [x] game informs player if the selected move is a draw move
- [x] game repeats all actions for the next player's move
- [x] A loop is needed in this game that call actions repeated for each move
### Implement these features and submit for another review. Good luck.
- Happy coding!

By Raymond
Slack @iamraymond

**Comment by Victorgonbu** [comment]
Implemented requested changes. Thank you very much for reviewing @rOluochKe.

**Review by Dandush03 — COMMENTED** [review]
# Status: 🚀 Project Approved 🚀 

# Keep up your good work in the next milestone

# Happy Coding! 🤓 🤓

**Comment by Victorgonbu** [comment]
Thank you @Dandush03, have a nice day.

**Pull request merged**
